services:
  opengravity-agent:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: opengravity_agent
    restart: unless-stopped
    env_file:
      - .env
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: ${GOOGLE_APPLICATION_CREDENTIALS}
    volumes:
      - "${FIREBASE_CREDENTIALS_HOST_PATH}:${GOOGLE_APPLICATION_CREDENTIALS}:ro"
    networks:
      - Agente_obras

networks:
  Agente_obras:
    external: true
    name: Agente_obras
